// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelsDB;

namespace EntityFrameworkSafeUpdate.Migrations
{
    [DbContext(typeof(ModelsDbContext))]
    [Migration("20220123211113_SiteData_Edit001")]
    partial class SiteData_Edit001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("ModelsDB.SiteData", b =>
                {
                    b.Property<long>("idSiteData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<ulong>("VisitTotal")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("VisitTotalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("idSiteData");

                    b.ToTable("SiteData");

                    b.HasData(
                        new
                        {
                            idSiteData = 1L,
                            VisitTotal = 0ul,
                            VisitTotalCount = 0ul
                        });
                });

            modelBuilder.Entity("ModelsDB.SiteData_VisitToday", b =>
                {
                    b.Property<long>("idSiteData_VisitToday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("idSiteData_VisitToday");

                    b.ToTable("SiteData_VisitToday");
                });
#pragma warning restore 612, 618
        }
    }
}
